// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var blockedNum = "Hello Mom and Dad";

var Car = {
  brand: "BMW"
};

var Bike = {
  brand: "Kawasaki"
};

var thisIsLetBinding = "My Name Is Rizki";

var message = "Hi Mom";

exports.thisIsLetBinding = thisIsLetBinding;
exports.message = message;
exports.blockedNum = blockedNum;
exports.Car = Car;
exports.Bike = Bike;
/* No side effect */
