// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function smartInference(a, b) {
  return a + b | 0;
}

function greetMom(from, message) {
  return "It's me " + from + " " + message;
}

var cashInWallet = 130;

var name = "rizki";

var age = 24;

var yourName = "Rizz";

exports.cashInWallet = cashInWallet;
exports.smartInference = smartInference;
exports.name = name;
exports.age = age;
exports.greetMom = greetMom;
exports.yourName = yourName;
/* No side effect */
