// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function takesTwo(a, b) {
  return a + b | 0;
}

function increment(value) {
  return value + 1 | 0;
}

function incrementBy(value, by) {
  return value + by | 0;
}

var Add = {
  takesTwo: takesTwo,
  increment: increment,
  incrementBy: incrementBy
};

exports.Add = Add;
/* No side effect */
