// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function multiply(a) {
  return (a << 1);
}

function multiplyBy(value, by) {
  return Math.imul(value, by);
}

function power(value) {
  return Math.pow(value, value);
}

var Multiply = {
  multiply: multiply,
  multiplyBy: multiplyBy,
  power: power
};

exports.Multiply = Multiply;
/* No side effect */
